const supportTelegramHandle = '@Freshman_tricks_admin';
const supportTelegramUrl = 'https://t.me/freshman_tricks_admin';
const supportPhoneNumber = '0902100732';
const supportPhoneUrl = 'tel:0902100732';
const supportEmail = 'freshmantricks2015@gmail.com';
const supportEmailUrl =
    'mailto:freshmantricks2015@gmail.com?subject=Freshman%20Support';
const supportWebsiteHost = 'entrancetricks.com';
const supportWebsiteUrl = 'https://entrancetricks.com';
